version: 2.1
jobs:
  compile:
   docker:
      - image: ubuntu:latest
   steps:
      - run:
          command: |
           apt-get update && \
           apt-get upgrade -y && \
           apt-get install -y git
           git config --global user.name "kingsmankdi"
           git config --global user.email "gupta2502chirag@gmail.com"
           git config --global color.ui true
           git clone https://github.com/flashokiller/circleci-aosp
           cd circleci-aosp
           bash .circleci/build.sh
workflows:
  version: 2.1
  cooking:
    jobs:
      - compile

